version: 2
jobs:
  build:
    working_directory: ~/inspections
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: inspectionist
          RAILS_ENV: test
      - image: circleci/postgres:9.4.12-alpine
        environtment:
          POSTGRES_USER: inspectionist
          POSTGRES_DB: inspections_test
          POSTGRES_PASSWORD:
    steps:
      - checkout

      - type: cache-restore
        name: Restore bundle cache
        key: inspections-bundle-{{ checksum "Gemfile.lock" }}

      - type: cache-restore
        name: Restore yarn cache
        key: inspections-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Bundle install
          command: bin/bundle install --path vendor/bundle

      - run:
          name: Yarn install
          command: yarn install

      - type: cache-save
        name: Store bundle cache
        key: inspections-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: cache-save
        name: Store yarn cache
        key: inspections-yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.yarn-cache

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Run rspec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress

      - type: store_test_results
        path: /tmp/test-results
